DROP TABLE STAFF;
CREATE TABLE STAFF(
    SNO     VARCHAR2(5 BYTE)        NOT NULL,  -- 사원 번호
    NAME    VARCHAR2(32 BYTE)               ,  -- 이름
    DEPT    VARCHAR2(20 BYTE)       NOT NULL,  -- 부서
    SALARY  NUMBER                  NOT NULL,  -- 연봉 
    CONSTRAINT PK_STAFF PRIMARY KEY(SNO)
);

SELECT SNO,NAME,DEPT,SALARY 
FROM STAFF
ORDER BY DESC;